- url: http://blog.swessel.me
  alt: blog
  icon: fa-home
- url: https://github.com/gr4y
  alt: GitHub
  icon: fa-github
- url: http://instagram.com/gr4yweb
  alt: Instagram
  icon: fa-instagram
- url: http://flickr.com/photos/gr4yweb
  alt: flickr
  icon: fa-flickr
- url: https://plus.google.com/+SaschaWessel
  alt: Google+
  icon: fa-google-plus
- url: http://gr4y.tumblr.com
  alt: Tumblr
  icon: fa-tumblr
